[apple]
# Key ID for the given private key, described in App Store Connect
KeyID="xxxx"
# Issuer ID for the App Store Connect team
IssuerID="xxxx"
# A duration value for the lifetime of a token. App Store Connect does not accept a token with a lifetime of longer than 20 minutes
ExpiryDuration ="20m"
# The bytes of the PKCS#8 private key created on App Store Connect. Keep this key safe as you can only download it once.
PrivateKeyFile ="/path/xxxx.p8"
[google]
GOOGLE_APPLICATION_CREDENTIALS=""